extends: spectral:oas

except:
  # Endpoints for browsers so expected behaviour is a 302 redirect
  "specs/openapi.v1.yaml#/paths/~1authorize/get/responses":
    - operation-2xx-response
  "specs/openapi.v1.yaml#/paths/~1sessions~1logout/get/responses":
    - operation-2xx-response

rules:

  # See https://stoplight.io/p/docs/gh/stoplightio/spectral/docs/guides/4-custom-rulesets.md?srn=gh/stoplightio/spectral/docs/guides/4-custom-rulesets.md 
  parameter-snake-case-name:
    description: parameter name should be snake_case.
    type: style
    severity: error
    given: $..parameters..name
    then:
      function: casing
      functionOptions:
        type: snake

  properties-descriptions:
    description: all properties children should have a description
    severity: error
    given: $..properties.*
    then:
      field: description
      function: truthy