extends: spectral:oas
rules:

  parameter-snake-case-name:
    description: parameter name should be snake_case.
    type: style
    severity: error
    given: $..parameters..name
    then:
      function: casing
      functionOptions:
        type: snake    