openapi: 3.0.0
info:
  title: tru.ID APIs
  version: v0.1
  contact:
    name: tru.ID API Team
    email: feedback@tru.id
  description: |
    # Introduction

    The tru.ID API uses [OAuth2](#tag/oauth2) Access Tokens for authentication. Access Tokens are created using the [/token endpoint](#operation/oauth2-token) with a valid `client_id` and `client_secret`. `client_id` and `client_secret` credentials are obtained by [creating a Project](#operation/create-project).

    The [**tru.ID PhoneCheck Workflow** and API](#tag/phone_check) confirms the ownership of a mobile phone number by verifying the possession of an active SIM card with the same number. A mobile data session is created to a unique **PhoneCheck URL** for the purpose of this verification. **tru.ID** then resolves a **PhoneCheck Match** between the phone number that the mobile network operator identifies as the owner of the mobile data session and the phone number being verified.

    The [**tru.ID SIMCheck API**](#tag/sim_check) provides information on when a SIM card associated with a mobile phone number last changed

    The [**tru.ID SubscriberCheck Workflow** and API](#tag/subscriber_check) combines the functionality offerd by PhoneCheck and SIMCheck into a single API. It confirms the ownership of a mobile phone number and provides information on when the SIM card associated with the mobile phone number last changed..
servers:
  - url: "https://{data_residency}.api.tru.id"
    description: For accounts with data residency in the EU
    variables:
      data_residency:
        default: eu
        enum:
          - eu
tags:
  - name: sim_check_v0.1
    x-displayName: v0.1
    description: Relating to SIMCheck

x-tagGroups:
  - name: SIMCheck
    tags:
      - sim_check_v0.1

paths:
  /sim_check/v0.1/checks:
    post:
      summary: Create a SIMCheck
      description: |
        Starts the SIMCheck
      operationId: create-sim-check
      security:
        - ProjectBearerAuth: []
      tags:
        - sim_check_v0.1
      requestBody:
        description: JSON payload to create a SIMCheck
        content:
          application/json:
            schema:
              $ref: ./models/sim_check/SimCheckResourceModels.v1.yaml#/components/schemas/SimCheckCreatePayload
      responses:
        "201":
          description: SIMCheck created
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                allOf:
                  - $ref: ./models/sim_check/SimCheckResourceModels.v1.yaml#/components/schemas/SimCheck
                  - type: object
                    properties:
                      status:
                        description: The current status of the SIMCheck
                        type: string
                        enum:
                          - COMPLETED
                          - ERROR
                        example: COMPLETED
                      snapshot_balance:
                        description: |
                          The workspace balance in `charge_currency` taking into account the `charge_amount`.
                          This property is not persisted and is only returned when the SIMCheck is initially created.
                        type: number
                        example: 100
        "400":
          description: Mobile Network Operator Not Supported
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/MobileNetworkOperatorNotSupported
        "412":
          description: Not a mobile IP
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotMobileIp
    get:
      summary: Get a collection of SIMChecks
      operationId: get-sim-checks
      description: Get a full list of SIMChecks or filter by query parameter.
      security:
        - ProjectBearerAuth: []
      tags:
        - sim_check_v0.1
      parameters:
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/pageSize
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/pageNumber
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/search
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/sort
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/sim_check/SimCheckResourceModels.v1.yaml#/components/schemas/SimCheckCollection
  "/sim_check/v0.1/checks/{check_id}":
    parameters:
      - name: check_id
        description: The ID of the SIMCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
    get:
      summary: Get SIMCheck
      description: Get a SIMCheck identified by `check_id`.
      operationId: get-sim-check
      security:
        - ProjectBearerAuth: []
      tags:
        - sim_check_v0.1
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/sim_check/SimCheckResourceModels.v1.yaml#/components/schemas/SimCheck
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
  "/sim_check/v0.1/checks/{check_id}/traces":
    parameters:
      - name: check_id
        description: The ID of the SIMCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
    get:
      summary: Get a collection of SIMCheck Traces
      description: Get Traces of the SIMCheck identified by `check_id`
      operationId: get-sim-check-traces
      tags:
        - sim_check_v0.1
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/trace/TraceResourceModels.v1.yaml#/components/schemas/TraceCollection
              examples:
                basic:
                  value:
                    _embedded:
                      traces:
                        - _links:
                            self:
                              href: "https://eu.api.tru.id/sim_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces/6f2a0e25fc0caa25"
                          trace_id: 6f2a0e25fc0caa25
                          logs:
                            - timestamp: "2021-02-05T13:58:48.751Z"
                              message: "Check create: phone number is reachable"
                            - timestamp: "2021-02-05T13:58:48.856Z"
                              message: "Check balance: authorized"
                              attributes:
                                amount: 1
                                currency: API
                            - timestamp: "2021-02-05T13:58:48.864Z"
                              message: "Check create: accepted"
                        - _links:
                            self:
                              href: "https://eu.api.tru.id/sim_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces/7f1bc78ab197ee8b"
                          trace_id: 7f1bc78ab197ee8b
                          logs:
                            - timestamp: "2021-02-05T13:59:05.060Z"
                              message: "Check balance: confirmed"
                              attributes:
                                amount: 1
                                currency: API
                    _links:
                      self:
                        href: "https://eu.api.tru.id/sim_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
  "/sim_check/v0.1/checks/{check_id}/traces/{trace_id}":
    parameters:
      - name: check_id
        description: The ID of the SIMCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
      - name: trace_id
        description: The ID of the of the trace
        schema:
          type: string
        in: path
        required: true
    get:
      summary: Get Simcheck Trace
      description: Get the Trace identified by `trace_id`  of the SIMCheck identified by `check_id`
      operationId: get-sim-check-trace
      tags:
        - sim_check_v0.1
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/trace/TraceResourceModels.v1.yaml#/components/schemas/TraceResource
              examples:
                basic:
                  value:
                    trace_id: 6f2a0e25fc0caa25
                    logs:
                      - timestamp: "2021-02-05T13:58:48.751Z"
                        message: "Check create: request accepted"
                      - timestamp: "2021-02-05T13:58:48.824Z"
                        message: "Check create: phone number is routable"
                      - timestamp: "2021-02-05T13:58:48.856Z"
                        message: "Check balance: authorized"
                        attributes:
                          amount: 1
                          currency_code: API
                      - timestamp: "2021-02-05T13:58:48.864Z"
                        message: "Check create: successful"
                    _links:
                      self:
                        href: "https://eu.api.tru.id/sim_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces/6f2a0e25fc0caa25"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
  "/coverage/v0.1/countries/{code}":
    parameters:
      - name: code
        schema:
          oneOf:
            - $ref: ./models/coverage/CoverageResourceModels.v1.yaml#/components/schemas/CountryCode
            - $ref: ./models/coverage/CoverageResourceModels.v1.yaml#/components/schemas/CountryDialingCode
        description: "Either two letter code [ISO 3166-1 alpha-2](https://www.iso.org/obp/ui/#iso:std:iso:3166:-3:ed-3:v1:en) or country dialing code"
        in: path
        required: true
        examples:
          country_code:
            value: GB
            summary: United Kingdom Country Code
          dialing_code:
            value: 44
            summary: The dialing code for United Kingdom
    get:
      summary: Get Country Coverage
      description: |
        Get the country product coverage by country code.

        Project-level authentication (`client_id` and `client_secret`) is required. Associated pricing for the countries in the API response are based on the Workspace that the Project is associated with.
      operationId: get-coverage-by-code
      security:
        - ProjectBearerAuth: []
      tags:
        - coverage
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/coverage/CoverageResourceModels.v1.yaml#/components/schemas/CountryCoverage
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "404":
          description: No Reach
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
  "/coverage/v0.1/device_ips/{ip}":
    parameters:
      - name: ip
        schema:
          type: string
          format: ipv4 | ipv6
        description: The device ip in ipv4 or ipv6 format
        in: path
        required: true
    get:
      summary: Get Device Reachability
      description: Get the mobile network that a device is on along with products that are supported based on device IP address.
      operationId: get-coverage-by-device-ip
      security:
        - ProjectBearerAuth: []
      tags:
        - coverage
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/coverage/CoverageResourceModels.v1.yaml#/components/schemas/DeviceReachability
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "400":
          description: MNO Not Supported
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/MobileNetworkOperatorNotSupported
        "412":
          description: Not a mobile IP
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotMobileIp
  
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    WorkspaceBearerAuth:
      description: |
        The tru.ID APIs expect the bearer token to be a [OAuth2 Access Token](https://tools.ietf.org/html/rfc6749#section-1.4). The access token should be within the `Authorization` HTTP header.
        e.g. `Authorization: Bearer {access_token}`

        The token should be a Workspace-level access token. These are created using your Workspace `client_id` and `client_secret`.
      type: http
      scheme: bearer
    ProjectBearerAuth:
      description: |
        The tru.ID APIs expect the bearer token to be a [OAuth2 Access Token](https://tools.ietf.org/html/rfc6749#section-1.4). The access token should be within the `Authorization` HTTP header.
        e.g. `Authorization: Bearer {access_token}`. See [Create an Access Token](#operation/oauth2-token).

        The token should be associated with **tru.ID** Project. These are created using a Project `client_id` and `client_secret`. See [Create an Access Token](#operation/oauth2-token).
      type: http
      scheme: bearer
    UserBearerAuth:
      type: http
      scheme: bearer
  schemas:
    OAuth2Scope:
      description: |
        The scope of the access request. A spaced delimited list of scopes representing the resources the Access Token provides access to.

        - `console`: `/console/{version}` resources. From version 0.2.
        - `projects`: `/console/v0.1/projects` resources
        - `workspaces`: `/console/v0.1/workspaces` resources
        - `phone_check`: `/phone_check` resources
        - `subscriber_check`: `/subscriber_check` resources
        - `sim_check`: `/sim_check` resources
        - `coverage`: `/coverage` resources
        - `usage`: `/console/v0.1/workspaces/default/usage` resources
      type: string
      example: phone_check subscriber_check sim_check
  parameters:
    scope:
      name: scope
      description: |
        A spaced delimited list of scopes representing the resources the Access Token provides access to.
      in: query
      schema:
        $ref: "#/components/schemas/OAuth2Scope"
